### ISSUE TITLE
1.13 的修改计划

### ISSUE THREAD

**Issue by phoenixlzx** [NyaaCat/InfernalMobs#13]
- [x] 到出生点的距离控制等级
- [x] 设定每个等级怪物的：
  - 血量
  - 经验
  - 伤害
  - 抗性或减伤百分比
- [x] 设定技能的等级（设定此技能仅在某些等级出现，不设定即可能在每个等级出现
- [ ] 优化一些战斗逻辑和技能的使用（开发组内讨论 @miu-wen 
- [ ] 对血月插件提供更好的 API [低优先级]
- [x] 一些特定的怪物（通过 NBT Tag
- [ ] 高优先 - 怪物技能实例（类似 rgi power）

通用怪物设定上例如：

```
mobConfig:
  level-1:
    health: 60 # 60 pts of health
    exp: 8 # 8 pts exp when die
    damage: 10 # attackDamage set to 10
    armor: 5 # reduce 5% of damage taken
```

通过 NBT 设定的怪物，可以单独写一个配置文件 `mobs.yml`

```
mobs:
  spiderking:
    name: SpiderKing # the name tag shows [prefix] SpiderKing [level] ... as the template defined in config
    levels:
    - 5
    - 6
    - 7
    abilities:  # leave blank for none, 'random' for random abilities
    - sprint
    - webber
    nbttags: {Attributes:[{Name:generic.maxHealth,Base:50},{Name:generic.movementSpeed,Base:0.9},{Name:generic.attackDamage,Base:20},{Name:generic.followRange,Base:50},{Name:generic.knockbackResistance,Base:0.2},{Name:generic.armor,Base:10}]}
```

特定怪物的其他设定继承 `mobConfig` 中的内容，掉落额外继承 `loot_v2` 的内容。

技能等级相关 `ability.yml`

```
abilities:
  sprint:
    enabled: true
    levels:
    - 1
    - 2
    - 10-12
...
```

**Comment by Acappellia** [comment]
一些个人的想法：

- 怪物血量能够显示到bossbar上面
- 怪物的技能也能有强弱之分（比如可以和怪物等级相关）
- 怪物等级不只和与出生点距离相关，还有别的因素（比如biome），甚至可以手动设置特定范围刷新特定黑化怪物

**Comment by miu-wen** [comment]
- 怪物掉落可以设定某个区域内掉落特定的物品
- 怪物技能可以进行连接触发（例如，引力过来之后再执行扔高）
- 增加可以直接召唤特殊定制好的怪物的指令

**Comment by phoenixlzx** [comment]
* 性能优化
* 取消记分板，改用 bossbar 展示血量（优先展示光标下的生物，然后是最近的生物，最多展示 3 个 Bossbar 之类）
* 命令处理修复

**Comment by phoenixlzx** [comment]
自定义生物的掉落可以从 loot_v2 选取

```
mobs:
  spiderking:
    __class__: com.jacob_vejvoda.infernal_mobs.config.CustomMobConfig$CustomMob
    name: SpiderKing # the name tag shows [prefix] SpiderKing [level] ... as the template defined in config
    type: SPIDER
    levels:
      - 5
      - 6
      - 7
    abilities:  # leave blank for none, 'random' for random abilities
      - sprint
      - webber
    nbttags: "{Attributes:[{Name:generic.maxHealth,Base:50},{Name:generic.movementSpeed,Base:0.9},{Name:generic.attackDamage,Base:20},{Name:generic.followRange,Base:50},{Name:generic.knockbackResistance,Base:0.2},{Name:generic.armor,Base:10}]}"
    spawnChance: 50
    canAutoSpawn: true
    loot:
    - gem:100  # loot_v2 中的掉落物名称:权重
    - sword:200
```

以及生成命令

```
/im sm [mob name]
```

在鼠标指向位置生成此 mob
